### PR TITLE
Improvements related to copyright header

### PR DESCRIPTION
**Pull request by akurinnoy**
Signed-off-by: Oleksii Kurinnyi <okurinny@redhat.com>

- added `eslint-plugin-notice`. It checks the top of specified files for the copyright header.
- re-added `husky` to lint only staged code on before git commit and test code on before git push.

### CODE REVIEW

**Comment by olexii4** [comment]
@akurinnoy Rerun **bump-deps** and add changes into this PR

**Comment by olexii4** [comment]
Maybe we should really changed '2018-2020' -> '2020-2020'.
After all, I agreed with a proposal from @sleshchenko about years.

It doesn't work for me. I add a change
 '* Copyright (c) 2018-2020 Red Hat, Inc.' -> '* Copyright (c) 2018-200 Red Hat, Inc.'
And can add a commit after.
```
        modified:   src/index.tsx

➜  che-dashboard-next git:(update-license-check) ✗ git commit -m "tmp" -s
husky > pre-commit (node v10.20.1)
✔ Preparing...
✔ Running tasks...
✔ Applying modifications...
✔ Cleaning up... 
[update-license-check 107b1d3] tmp
 2 files changed, 31 insertions(+), 52 deletions(-)
➜  che-dashboard-next git:(update-license-check) git st 
On branch update-license-check
Your branch is ahead of 'origin/update-license-check' by 1 commit.
  (use "git push" to publish your local commits)

nothing to commit, working tree clean
➜  che-dashboard-next git:(update-license-check) 
```

It shouldn't be in the case with 
```
  'hooks': {
    'pre-commit': 'lint-staged',
    'pre-push': 'yarn test',
  },
```

**Comment by olexii4** [comment]
-1

**Comment by olexii4** [comment]
@akurinnoy Oh. I see. It just fixed errors before a commit without any warnings or errors. And my editor did not update the page after.
No problem. But I think it is better to run the fix tusk manually.
WDYT?

**Comment by akurinnoy** [comment]
@olexii4 I've updated eslint plugin config to fail if a file header doesn't match the template

**Comment by olexii4** [comment]
@akurinnoy Run **yarn format** and add changes into this PR too.

**Review by olexii4 — APPROVED** [review]

**Review by sleshchenko — APPROVED** [review]

**Pull request merged**
